###CREATE NEW USER
POST http://localhost:3333/auth/register
Content-Type: application/json

{
  "name":"sertorius",
  "email":"sertorius@scipio.com",
  "password":"12345678"
}

###LOGIN USER
POST http://localhost:3333/auth/login
Content-Type: application/json

{
  "email":"sertorius@scipio.com",
  "password":"12345678"
}

### RUTA PROTEGIDA
GET http://localhost:3333/order