###CREATE NEW USER
POST http://localhost:3333/auth/register
Content-Type: application/json

{
  "name":"sertorius",
  "email":"st@scipio.com",
  "password":""
}

###LOGIN USER
POST http://localhost:3333/auth/login
Content-Type: application/json

{
  "email":"sts@scipio.com",
  "password":""
}

### RUTA PROTEGIDA
GET http://localhost:3333/order
Authorization: Bearer XXX